### ISSUE TITLE
Error: QWeb2: Template 'website.fullscreen_indication' not found

### ISSUE THREAD

**Issue by lesdekock** [pga-odoo/OdooDebug#17]
Using Odoo 15.0

When debug mode is off the following error is reported but not when debug mode is on or asset debug is on:

Error: QWeb2: Template 'website.fullscreen_indication' not found
    at Object.exception (https://***.*******.***/web/assets/2689-e152a15/1/web.assets_common_lazy.min.js:4316:7)
    at Engine._render (https://***.*******.***/web/assets/2689-e152a15/1/web.assets_common_lazy.min.js:4360:103)
    at Engine.render (https://***.*******.***/web/assets/2689-e152a15/1/web.assets_common_lazy.min.js:4356:151)
    at Class.renderElement (https://***.*******.***/web/assets/2689-e152a15/1/web.assets_common_lazy.min.js:4922:775)
    at https://***.*******.***/web/assets/2689-e152a15/1/web.assets_common_lazy.min.js:4932:6
    at async Promise.all (index 1)
    at async Promise.all (index 1)
    at async createPublicRoot (https://***.*******.***/web/assets/2690-c8678e1/1/web.assets_frontend_lazy.min.js:1583:335)

**Comment by lesdekock** [comment]
This does not seem to be an issue with the plugin.
